
sonata_block:
    blocks:
        sonata_translation.block.locale_switcher:

sonata_admin:
    extensions:
        sonata_translation.admin.extension.gedmo_translatable:
            extends:
                - Sonata\TranslationBundle\Model\Gedmo\AbstractTranslatable

